spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=UTF-8&serverTimezone=UCT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    generate-ddl: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always